# Dependencies

# Plugins
plugins:
    - jekyll-paginate
    - jekyll-seo-tag

# Permalinks
permalink:        pretty

# Setup
title:            Sherlock Holmes & the NSA
tagline:          OpenSource Intelligence
description:      Descendons dans le terrier du lapin blanc avec l'OSINT, l'OpenSource Intelligence.
url:              https://bornlex.github.io
baseurl:          /

author:
  name:           'Julien Seveno-Piltant'
  url:            https://bornlex.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Bornlex/bornlex.github.io