# Dependencies

# Plugins
plugins:
    - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Sherlock Holmes & the NSA
tagline:          Prenez ma main et descendons ensemble dans le terrier du lapin blanc a la decouverte de l'OSINT, l'OpenSource Intelligence.
description:      Prenez ma main et descendons ensemble dans le terrier du lapin blanc a la decouverte de l'OSINT, l'OpenSource Intelligence.
url:              http://bornlex.github.io
baseurl:          /

author:
  name:           'Julien Seveno-Piltant'
  url:            https://bornlex.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Bornlex/bornlex.github.io